### PR TITLE
Add FASTA parser

### PR DESCRIPTION
**Pull request by JacopoTeneggi**

### CODE REVIEW

**Comment by JacopoTeneggi** [comment]
Btw, when I try to run `dune build` I get the following error messages
```bash
File "src/pfp.ml", line 120, characters 55-68:
120 |       parse |> IntSequence.of_list |> IntBWT.getBWT |> List.of_array
                                                             ^^^^^^^^^^^^^
Error: Unbound value List.of_array
Hint: Did you mean to_array?
```

can y'all reproduce this behavior or is it me?

**Comment by vshiv18** [comment]
Might just be you. I'm worried installing the biocaml stuff messed up some opam/core versioning?

**Comment by vshiv18** [comment]
It is certainly a function in Core: https://ocaml.org/p/core/v0.16.2/doc/Core/List/index.html#val-of_array

**Comment by JacopoTeneggi** [comment]
Cool yea it was biocaml!

**Pull request merged**
